### ISSUE TITLE
Google Play edit API return 500-internal service error

### ISSUE THREAD

**Issue by jimmygns** [googleapis/google-api-java-client#1085]
I'm trying to run a quick update on my personal info using Google Play APIs(Java client). It fails on when I try to commit this edit. Did anyone experience this too?
Here is the stack trace.:

```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
{
  "code" : 500,
  "message" : null
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.appscatter.apppublishingexecutors.store.googleplay.utils.GoogleObject.commitEdit(GoogleObject.java:245)
	... 8 common frames omitted
```

The code I wrote is pretty straightforward, similar to the Java sample codebase.

**Comment by sduskis** [comment]
I'm closing this due to staleness.  This is something that we would have needed much more debugging information, and probably just suggest that the Google Play support is used (https://support.google.com/googleplay/?hl=en#topic=3364260)
