### ISSUE TITLE
Possible Regression in MockTokenServerTransport

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-api-java-client#1151]
Following test case used to work in `google-api-client` 1.23.0, but breaks in 1.25.0:

```
@Test
  public void testMe() throws IOException {
    final MockTokenServerTransport transport = new MockTokenServerTransport();
    transport.addServiceAccount(ServiceAccount.EDITOR.getEmail(), ACCESS_TOKEN);
    ServiceAccountCredentials creds = ServiceAccountCredentials.fromStream(ServiceAccount.EDITOR.asStream(),
        new HttpTransportFactory() {
          @Override
          public HttpTransport create() {
            return transport;
          }
        });
    GoogleCredentials scoped = creds.createScoped(
        ImmutableList.of("https://www.googleapis.com/auth/cloud-platform"));
    assertNotNull(scoped.refreshAccessToken());
  }
```

In the latest version I must pass in the URL `"https://accounts.google.com/o/oauth2/token"` to the `MockTokenServerTransport`. Is this intentional or a regression?

**Comment by chingor13** [comment]
This was likely due to a mismatch in versions between google-auth-library-java and google-api-java-client. We needed to upgrade the oauth token endpoint off of a deprecated one and it was across 2 separate libraries.

It's likely you were testing an older google-auth-library-java version against the newer google-api-client. The endpoints should be in sync in the latest versions.

**Comment by hiranya911** [comment]
I still cannot get the above test case to pass without passing in the server URL :(

```
java.lang.NullPointerException
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127)
	at com.google.api.client.json.jackson2.JacksonFactory.createJsonParser(JacksonFactory.java:92)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:85)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:398)
	at com.google.firebase.FirebaseAppTest.testMe(FirebaseAppTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

My project has google-api-client 1.25.0 and google-auth-library 0.11.0.

**Comment by hiranya911** [comment]
Get the same error with google-api-cleint 1.27.0 and google-auth-library 0.12.0. Those are the latest versions. Please reopen this issue.

**Comment by chingor13** [comment]
Ah, so here's what's happening: `ServiceAccountCredentials` reads the `token_uri` value from the service account JSON file provided. Older versions of the service account JSON files specified `https://accounts.google.com/o/oauth2/token` as the endpoint while newer ones use `https://oauth2.googleapis.com/token`. The `MockTokenServerTransport` defaults to only checking the newest endpoint URL for returning content.

**Comment by chingor13** [comment]
In #1232, we are handling the legacy endpoint for backwards compatibility while logging a warning message to update your credentials file.
