### ISSUE TITLE
Remove or replace DataNucleus

### ISSUE THREAD

**Issue by elharo** [googleapis/google-api-java-client#1167]
DataNucleus doesn't work very well on App Engine these days and the official recommendation is to replace it: https://cloud.google.com/appengine/docs/standard/java/datastore/jdo/overview-dn2

I'm not sure how deeply DataNucleus is woven into this project, but if it's not too tight we should get rid of it.

**Comment by elharo** [comment]
Looks like we can just take it out:

>>  /Users/elharo/.m2/repository/javax/jdo/jdo2-api/2.3-eb/jdo2-api-2.3-eb.jar
>>  /Users/elharo/.m2/repository/javax/transaction/transaction-api/1.1/transaction-api-1.1.jar
DataNucleus Enhancer completed with success for 0 classes. Timings : input=94 ms, enhance=0 ms, total=94 ms. Consult the log for full details
DataNucleus Enhancer completed and no classes were enhanced. Consult the log for full details

[ERROR] --------------------
[ERROR]  Standard error from the DataNucleus tool + org.datanucleus.enhancer.DataNucleusEnhancer :
[ERROR] --------------------
[ERROR] Sep 21, 2018 7:10:43 AM org.datanucleus.enhancer.DataNucleusEnhancer <init>
INFO: DataNucleus Enhancer : Using ClassEnhancer "ASM" for API "JDO"
Sep 21, 2018 7:10:43 AM org.datanucleus.enhancer.DataNucleusEnhancer main
INFO: DataNucleus Enhancer (version 2.1.3) : Enhancement of classes
Sep 21, 2018 7:10:43 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.servlet.notifications.NotificationServlet" has no MetaData or annotations.
Sep 21, 2018 7:10:43 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.servlet.notifications.package-info" has no MetaData or annotations.
Sep 21, 2018 7:10:43 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.servlet.notifications.WebhookUtils" has no MetaData or annotations.
Sep 21, 2018 7:10:43 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.servlet.notifications.WebhookHeaders" has no MetaData or annotations.
Sep 21, 2018 7:10:43 AM org.datanucleus.enhancer.DataNucleusEnhancer addMessage
INFO: DataNucleus Enhancer completed with success for 0 classes. Timings : input=94 ms, enhance=0 ms, total=94 ms. Consult the log for full details
Sep 21, 2018 7:10:43 AM org.datanucleus.enhancer.DataNucleusEnhancer main
INFO: DataNucleus Enhancer completed and no classes were enhanced. Consult the log for full details

**Comment by elharo** [comment]
And

[ERROR] --------------------
[ERROR]  Standard error from the DataNucleus tool + org.datanucleus.enhancer.DataNucleusEnhancer :
[ERROR] --------------------
[ERROR] Sep 21, 2018 7:10:47 AM org.datanucleus.enhancer.DataNucleusEnhancer <init>
INFO: DataNucleus Enhancer : Using ClassEnhancer "ASM" for API "JDO"
Sep 21, 2018 7:10:47 AM org.datanucleus.enhancer.DataNucleusEnhancer main
INFO: DataNucleus Enhancer (version 2.1.3) : Enhancement of classes
Sep 21, 2018 7:10:47 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.appengine.auth.oauth2.AppIdentityCredential$Builder" has no MetaData or annotations.
Sep 21, 2018 7:10:48 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.appengine.auth.oauth2.AppIdentityCredential$AppEngineCredentialWrapper" has no MetaData or annotations.
Sep 21, 2018 7:10:48 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.appengine.auth.oauth2.AppIdentityCredential" has no MetaData or annotations.
Sep 21, 2018 7:10:48 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.appengine.testing.auth.oauth2.package-info" has no MetaData or annotations.
Sep 21, 2018 7:10:48 AM org.datanucleus.metadata.MetaDataManager loadClasses
SEVERE: Class "com.google.api.client.googleapis.extensions.appengine.testing.auth.oauth2.MockAppIdentityService" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
org.datanucleus.exceptions.ClassNotResolvedException: Class "com.google.api.client.googleapis.extensions.appengine.testing.auth.oauth2.MockAppIdentityService" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:247)
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:412)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:436)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)

Sep 21, 2018 7:10:48 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.appengine.notifications.AppEngineNotificationServlet" has no MetaData or annotations.
Sep 21, 2018 7:10:48 AM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.googleapis.extensions.appengine.notifications.package-info" has no MetaData or annotations.
Sep 21, 2018 7:10:48 AM org.datanucleus.enhancer.DataNucleusEnhancer addMessage
INFO: DataNucleus Enhancer completed with success for 0 classes. Timings : input=106 ms, enhance=0 ms, total=106 ms. Consult the log for full details
Sep 21, 2018 7:10:48 AM org.datanucleus.enhancer.DataNucleusEnhancer main
INFO: DataNucleus Enhancer completed and no classes were enhanced. Consult the log for full details

[ERROR] --------------------
