### ISSUE TITLE
java.lang.IllegalArgumentException: key authorizationTimestamp API Client unable to parse response from Tag Manager

### ISSUE THREAD

**Issue by nate4d** [googleapis/google-api-java-client#1250]
When issue requests to Tag Manager v2 API 
https://www.googleapis.com/tagmanager/v2/+parent/environments
The 1.22 through 1.28 Java client versions are throwing a java.lang.IllegalArgumentException: key authorizationTimestamp

- Java version: 8
- google-api-java-client version:
1.22.0 through 1.28.0
google-api-services-tagmanager
v2-rev3-1.22.0 through v2-rev20190220-1.28.0

```
Environment env = new Environment();
env.setName("Test");
env.setContainerVersionId("1");
Environment createdEnv =
                tagManager.accounts().containers().environments()
                        .create("accounts/[accountId]/containers/[containerId]", env)
                        .execute();
```
#### Stacktrace

```
Exception in thread "main" java.lang.IllegalArgumentException: key authorizationTimestamp
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:382)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at gtmtest.Main.main(Main.java:21)
Caused by: java.lang.IllegalArgumentException: key authorizationTimestamp, field private com.google.api.services.tagmanager.model.Timestamp com.google.api.services.tagmanager.model.Environment.authorizationTimestamp
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:472)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)
	... 7 more
Caused by: java.lang.IllegalArgumentException: expected primitive class, but got: class com.google.api.services.tagmanager.model.Timestamp
	at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:453)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:859)
```
#### External references such as API reference guides used

https://developers.google.com/tag-manager/api/v2/reference/accounts/containers/environments/create
https://developers.google.com/api-client-library/java/apis/tagmanager/v2

**Comment by chingor13** [comment]
This was "fixed" in the discovery definition in `rev20190617` - it the field was changed to a `google-datetime` which is surfaced as a `String`. To fix it, you can upgrade your client to any `v2-rev20190617-xxx` version or later.

After `rev20190617`, `Environment#getAuthorizationTimestamp()` returns a `String` instead of a `Timestamp` which could not be parsed from the JSON response.
