### ISSUE TITLE
GooglePublicKeysManager doesn't work with IAP's keys

### ISSUE THREAD

**Issue by Capstan** [googleapis/google-api-java-client#1428]
**Is your feature request related to a problem? Please describe.**
I am trying to validate IAP JWTs per https://cloud.google.com/iap/docs/signed-headers-howto. Instead of writing my own, given it's just an alternative `GoogleIdToken`, I want to be able to use `GooglePublicKeysManager` with `GoogleIdTokenVerifier`. However, the URL that IAP publishes their keys are https://www.gstatic.com/iap/verify/public_key for JSON dictionary with `kid` claims or https://www.gstatic.com/iap/verify/public_key-jwk for [JWK](https://tools.ietf.org/html/rfc7517) format. The `GooglePublicKeysManager.Builder` however only takes a certs url and expects the contents to be `-----BEGIN CERTIFICATE-----` rather than `-----BEGIN PUBLIC KEY-----` and so fails to parse the results with a stack trace like:

```
Caused by: java.security.cert.CertificateException: Unable to initialize, java.io.IOException: Short read of DER length
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:198)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at com.google.api.client.googleapis.auth.oauth2.GooglePublicKeysManager.refresh(GooglePublicKeysManager.java:187)
	at com.google.api.client.googleapis.auth.oauth2.GooglePublicKeysManager.getPublicKeys(GooglePublicKeysManager.java:140)
```

**Describe the solution you'd like**
Make `GooglePublicKeysManager` take alternative producers of public keys, at least by different format, and then have an `IapPublicKeysManager` that supports it (or allow IAP to produce the same as an extension class). 

**Describe alternatives you've considered**
I will likely reimplement the parsing by adapting the Java sample on the same page, but that means that I stand the chance of getting it wrong, which is not what I want for the main auth pipeline.

**Comment by Capstan** [comment]
I have a working variant now using https://connect2id.com/products/nimbus-jose-jwt based the [IAP Java sample](https://cloud.google.com/iap/docs/signed-headers-howto#iap_validate_jwt-java). I have rebased my original attempt at using `GooglePublicKeysManager` on top.

One issue is that `JavaWebSignature` only supports `RS256` algorithm, but the IAP JWTs use `ES256`, which is apparently natively support by Java using `Signature.getInstance("SHA256withECDSA")`. That said, even if I add that support, it still fails to validate the signature. Still trying to surmount that.

Another oddity, is that even though the JWT has a `kid` Key ID parameter, the implementation in `GooglePublicKeysManager` loops over all the known public keys, rather than record them in a map keyed by `kid`.

**Comment by Capstan** [comment]
Figured out the signature error. JWS has the signature in the format of two sequential 32-byte integers. Java expects the signature to be in DER sequence, so the signature has to be transformed before calling `signatureAlgorithm.verify(signatureBytes)`. This is described in part in [this stackoverflow issue](https://stackoverflow.com/questions/56824921/java-security-signatureexception-invalid-encoding-for-signature-signature-vali/56827924#56827924).

**Comment by Capstan** [comment]
This is a simplistic approach for loading public keys directly rather than from certs, without fixing the nomenclature of the fields. I'm not sure if one can know a priori what `KeyFactory` to use generally:
```diff
--- a/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GooglePublicKeysManager.java
+++ b/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GooglePublicKeysManager.java
@@ -23,15 +23,19 @@ import com.google.api.client.json.JsonPa
 import com.google.api.client.json.JsonToken;
 import com.google.api.client.util.Beta;
 import com.google.api.client.util.Clock;
+import com.google.api.client.util.PemReader;
 import com.google.api.client.util.Preconditions;
 import com.google.api.client.util.SecurityUtils;
 import com.google.api.client.util.StringUtils;
 import java.io.ByteArrayInputStream;
 import java.io.IOException;
+import java.io.StringReader;
 import java.security.GeneralSecurityException;
+import java.security.KeyFactory;
 import java.security.PublicKey;
 import java.security.cert.CertificateFactory;
 import java.security.cert.X509Certificate;
+import java.security.spec.X509EncodedKeySpec;
 import java.util.ArrayList;
 import java.util.Collections;
 import java.util.List;
@@ -154,7 +158,7 @@ public class GooglePublicKeysManager {
   }
 
   /**
-   * Forces a refresh of the public certificates downloaded from {@link #getPublicCertsEncodedUrl}.
+   * Forces a refresh of the public keys downloaded from {@link #getPublicCertsEncodedUrl}.
    *
    * <p>
    * This method is automatically called from {@link #getPublicKeys()} if the public keys have not
@@ -167,7 +171,8 @@ public class GooglePublicKeysManager {
     try {
       publicKeys = new ArrayList<PublicKey>();
       // HTTP request to public endpoint
-      CertificateFactory factory = SecurityUtils.getX509CertificateFactory();
+      CertificateFactory certFactory = SecurityUtils.getX509CertificateFactory();
+      KeyFactory keyFactory = KeyFactory.getInstance("EC");
       HttpResponse certsResponse = transport.createRequestFactory()
           .buildGetRequest(new GenericUrl(publicCertsEncodedUrl)).execute();
       expirationTimeMilliseconds =
@@ -183,10 +188,17 @@ public class GooglePublicKeysManager {
       try {
         while (parser.nextToken() != JsonToken.END_OBJECT) {
           parser.nextToken();
-          String certValue = parser.getText();
-          X509Certificate x509Cert = (X509Certificate) factory.generateCertificate(
-              new ByteArrayInputStream(StringUtils.getBytesUtf8(certValue)));
-          publicKeys.add(x509Cert.getPublicKey());
+          String certsOrKeysValue = parser.getText();
+          if (certsOrKeysValue.startsWith("-----BEGIN PUBLIC KEY-----\n")) {
+            PemReader reader = new PemReader(new StringReader(certsOrKeysValue));
+            X509EncodedKeySpec keySpec = new X509EncodedKeySpec(
+                reader.readNextSection().getBase64DecodedBytes());
+            publicKeys.add(keyFactory.generatePublic(keySpec));
+          } else {
+            X509Certificate x509Cert = (X509Certificate) certFactory.generateCertificate(
+               new ByteArrayInputStream(StringUtils.getBytesUtf8(certsOrKeysValue)));
+            publicKeys.add(x509Cert.getPublicKey());
+          }
         }
         publicKeys = Collections.unmodifiableList(publicKeys);
       } finally {
```

This extends the validator to handle ES256 signatures. The DER converter is simplistic, but functional. I'd use Tink or BouncyCastle if that were an option:
```diff
--- a/google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java
+++ b/google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java
@@ -23,6 +23,7 @@ import com.google.api.client.util.Securi
 import com.google.api.client.util.StringUtils;
 import java.io.ByteArrayInputStream;
 import java.io.IOException;
+import java.math.BigInteger;
 import java.security.GeneralSecurityException;
 import java.security.KeyStore;
 import java.security.KeyStoreException;
@@ -32,6 +33,7 @@ import java.security.PublicKey;
 import java.security.Signature;
 import java.security.cert.X509Certificate;
 import java.util.ArrayList;
+import java.util.Arrays;
 import java.util.List;
 import javax.net.ssl.TrustManager;
 import javax.net.ssl.TrustManagerFactory;
@@ -376,11 +378,37 @@ public class JsonWebSignature extends Js
     return (Header) super.getHeader();
   }
 
+  private static byte[] ecdsaToDer(byte[] ecdsaSignature) throws GeneralSecurityException {
+    if (ecdsaSignature.length != 64) {
+      throw new GeneralSecurityException("bad signature length");
+    }
+    BigInteger r = new BigInteger(1, Arrays.copyOfRange(ecdsaSignature, 0, 32));
+    BigInteger s = new BigInteger(1, Arrays.copyOfRange(ecdsaSignature, 32, 64));
+
+    // Please look away from this horrible manual DER. (Use BouncyCastle?)
+    // or https://google.github.io/tink/javadoc/tink/1.2.1/com/google/crypto/tink/subtle/EllipticCurves.html#ecdsaIeee2Der-byte:A-
+    byte[] rBytes = r.toByteArray();
+    byte[] sBytes = s.toByteArray();
+    byte[] der = new byte[6 + rBytes.length + sBytes.length];
+    der[0] = 0x30;  // Tag of signature
+    der[1] = (byte)(der.length - 2);  // Length of signature
+    int offset = 2;
+    der[offset++] = 0x2;  // Tag of ASN1Integer
+    der[offset++] = (byte)rBytes.length;  // Length of r
+    System.arraycopy(rBytes, 0, der, offset, rBytes.length);
+    offset += rBytes.length;
+    der[offset++] = 0x2;  // Tag of ASN1Integer
+    der[offset++] = (byte)sBytes.length;  // Length of s
+    System.arraycopy(sBytes, 0, der, offset, sBytes.length);
+
+    return der;
+  }
+
   /**
    * Verifies the signature of the content.
    *
-   * <p>Currently only {@code "RS256"} algorithm is verified, but others may be added in the future.
-   * For any other algorithm it returns {@code false}.
+   * <p>Currently only {@code "RS256"} and {@code "ES256"} algorithms are verified, but others may
+   * be added in the future. For any other algorithm it returns {@code false}.
    *
    * @param publicKey public key
    * @return whether the algorithm is recognized and it is verified
@@ -389,12 +417,17 @@ public class JsonWebSignature extends Js
   public final boolean verifySignature(PublicKey publicKey) throws GeneralSecurityException {
     Signature signatureAlg = null;
     String algorithm = getHeader().getAlgorithm();
+    byte[] finalSignatureBytes;
     if ("RS256".equals(algorithm)) {
       signatureAlg = SecurityUtils.getSha256WithRsaSignatureAlgorithm();
+      finalSignatureBytes = signatureBytes;
+    } else if ("ES256".equals(algorithm)) {
+      signatureAlg = Signature.getInstance("SHA256withECDSA");
+      finalSignatureBytes = ecdsaToDer(signatureBytes);
     } else {
       return false;
     }
-    return SecurityUtils.verify(signatureAlg, publicKey, signatureBytes, signedContentBytes);
+    return SecurityUtils.verify(signatureAlg, publicKey, finalSignatureBytes, signedContentBytes);
   }
 
   /**
```

With these changes, I can do the following:
```java
    final GooglePublicKeysManager iapKeysManager =
        new GooglePublicKeysManager.Builder(new NetHttpTransport(), new JacksonFactory())
            .setPublicCertsEncodedUrl("https://www.gstatic.com/iap/verify/public_key")
            .build();
    return new GoogleIdTokenVerifier.Builder(iapKeysManager)
        .setIssuer(IAP_ISSUER_URL)
        .setAudience(ImmutableSet.of(expectedAudience))
        .build();
```

**Comment by Capstan** [comment]
[EllipticCurves.ecdsaIeee2Der](https://google.github.io/tink/javadoc/tink/1.2.1/com/google/crypto/tink/subtle/EllipticCurves.html#ecdsaIeee2Der-byte:A-) works and is an improvement, but the [warning is not to use the subtle package](https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#important-warnings), so presumably you'd want to use something higher level.

**Comment by chingor13** [comment]
We've including JWT verification into the [google-auth-library](https://github.com/googleapis/google-auth-library-java#verifying-jwt-tokens-beta) which is the preferred method for handling authentication for these clients. It should be able to handle ES256 and RS256 signatures (Google Federated Auth and IAP).
