### ISSUE TITLE
500 Internal Server Error received while getting the records using the google reporting service.

### ISSUE THREAD

**Issue by prateek13688** [googleapis/google-api-java-client#1524]
I am using the google reporting service to fetch the gsuite logs. 
When I am fetching the logs after setting the next page token received in the previous response, I get an internal server error.

**Code Snippet:**
Reports.Activities.List activityList = reportsService.activities().list(USER_KEY, googleReportType.name())
                .setStartTime(startGoogleTime.toStringRfc3339())
                .setEndTime(endGoogleTime.toStringRfc3339())
activityList.setPageToken(nextPageToken);
Activities result = activityList.execute();

Error
com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
{
  "code" : 500,
  "errors" : [ {
    "domain" : "global",
    "message" : "Backend Error",
    "reason" : "backendError"
  } ],
  "message" : "Backend Error"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1092)

**Comment by lingyun-zhu** [comment]
related problem:https://stackoverflow.com/questions/50019241/google-cloud-storage-throwing-error-for-multiple-large-file-uploads-concurrently
