### ISSUE TITLE
Batch request Gmail

### ISSUE THREAD

**Issue by alkutsy** [googleapis/google-api-java-client#1564]
Hello there,

According this page https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html batch endpoints was stopped working.

Is it possible to send batch request now?

OS: Ubuntu Linux 
Java version:  Open JDK 8
google-api-client version(s): 1.30.10

#### Code example

```java

   List<Message> testGmail(Set<String> messageIds, Gmail gmailService, String monitoringEmail) throws IOException {
    List<Message> messages = new ArrayList<>();
    if(!CollectionUtils.isEmpty(messageIds)) {
      JsonBatchCallback<Message> messageCallback = new JsonBatchCallback<Message>() {

        @Override
        public void onSuccess(Message m, HttpHeaders responseHeaders) {
          log.debug("Message details successfully retrieved: '{}'", m.getId());
          messages.add(m);
        }

        @Override
        public void onFailure(GoogleJsonError e, HttpHeaders responseHeaders) {
          log.info("Error while retrieving message details '{}'", e.getMessage());
        }
      };
      ExponentialBackOff backoff = new ExponentialBackOff.Builder()
              .setInitialIntervalMillis(500)
              .setMaxElapsedTimeMillis(900000)
              .setMaxIntervalMillis(6000)
              .setMultiplier(1.5)
              .setRandomizationFactor(0.5)
              .build();

      HttpRequestInitializer httpRequestInitializer = request ->
              request.setUnsuccessfulResponseHandler(new HttpBackOffUnsuccessfulResponseHandler(backoff));
      BatchRequest batch = gmailService.batch(httpRequestInitializer);
      for(String messageId : messageIds) {
        gmailService.users().messages().get(monitoringEmail, messageId).setFormat(GoogleMailService.MAIL_FORMAT_FULL).queue(batch, messageCallback);
      }
      batch.execute();
    }
    return messages;
  } 

```

#### Stack trace
```
2020-08-16 00:00:01.462  WARN 7 --- [scheduling-1] [sys] c.g.a.c.googleapis.batch.BatchRequest    : You are using the global batch endpoint which will soon be shut down. Please instantiate your BatchRequest via your service client's `batch(HttpRequestInitializer)` method. For an example, please see https://github.com/googleapis/google-api-java-client#batching.
2020-08-16 00:00:01.843 ERROR 7 --- [scheduling-1] [sys] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

com.google.api.client.http.HttpResponseException: 404 Not Found
Global HTTP Batch endpoint is deprecated. See https://g.co/cloud/global-batch-deprecation for info and migration steps.
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1094)
	at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:258)

```

#### External references such as API reference guides
https://googleapis.dev/java/google-api-client/latest/com/google/api/client/googleapis/batch/BatchRequest.html

Thanks!

**Comment by chingor13** [comment]
Thanks for filing this. What version of the google-api-services-gmail are you using?

**Comment by alkutsy** [comment]
Hi @chingor13,

That was my fault I forgot to update version for Gmail. With the latest version it is working as expected.

Many thanks, ticket can be closed.

BR, A
