### ISSUE TITLE
Precondition check failed

### ISSUE THREAD

**Issue by jed204** [googleapis/google-api-java-client#1648]
We are getting a '400 Bad Request' response from the Gmail API for a single user. The error message doesn't provide a lot of information. The user has been authenticated by OAuth and we are sending from 'me'. This works for all other users across different companies/domains and at this point we've only seen this with this single user, here is the error message we get:

```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Precondition check failed.",
    "reason" : "failedPrecondition"
  } ],
  "message" : "Precondition check failed.",
  "status" : "FAILED_PRECONDITION"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:444)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:542)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:475)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:592)
```

Here's how we are sending:

```
GoogleCredential credential = new GoogleCredential().setAccessToken(accessToken);
final NetHttpTransport HTTP_TRANSPORT = GoogleNetHttpTransport.newTrustedTransport();
Gmail service = new Gmail.Builder(HTTP_TRANSPORT, JacksonFactory.getDefaultInstance(), credential)
                    .setApplicationName("Application Name")
                    .build();

...

message = service.users().messages().send("me", message).execute();`
```

We've confirmed the 'From' matches the user's name and email address (originally thought this might be the precondition that is failing). The same code and message content sends from other user accounts with no issue. Is there a way to know what is failing here and how we can identify it?

**Comment by Neenu1995** [comment]
The team that manages the Gmail API will be able to provide more information on the issue. Try contacting them here :
https://developers.google.com/gmail/api/support

**Comment by LindaLawton** [comment]
Means that you are trying to use a service account but did not declare which user you would like to delegate to. What its trying to do is access the service accounts gmail account, google wont let you do that. This is normally done by using the setServiceAccountUser method.

However if i understand you correctly you are using a standard gmail account. To use service accounts with gmail you need to have a google workspace domain account. Then the admin of your domain will be able to set up [domain wide delegation](https://developers.google.com/admin-sdk/directory/v1/guides/delegation) for you. It will only work with domain emails.

You can not use a service account with a standard google gmail account.
