### ISSUE TITLE
Google drive API (v2) Unable to download few files (.xlsx,pdf) with content, "BadRequest" 

### ISSUE THREAD

**Issue by rvirsingh** [googleapis/google-api-java-client#1910]
I am trying to download documents/files store in google drive using google drive API version (V2). though I am able to download files successfully except few non google docs (.xlsx, pdf)  that are failing with Bad request.
I have tried rest API approach
https://developers.google.com/drive/api/v2/reference/files/get
as well as native SDK method:
https://developers.google.com/drive/api/v2/manage-downloads#download_a_file_stored_on_google_drive
Code snipped to download non google file:

It is also not throwing proper JSON error object as described here [Error Resource](https://cloud.google.com/resource-manager/docs/core_errors)
But nothing working and there is nothing in error logs except below:

 

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

#### Environment details

1. OS type and version: Debian
2. Java version: openjdk-11-jre-headless:amd64  11.0.12+7-2~deb10u1
3. google-api-client version(s): 1.25.0
4. Google drive api version: v2-rev387-1.25.0

#### Steps to reproduce

It is happening in Production environment and not reproducible in any other environments

#### Code example

```java
public InputStream download() throws IOException {
    HttpRequest httpRequest = service.getRequestFactory().buildGetRequest(new GenericUrl(file.getDownloadUrl()));
    try {
        return httpRequest.execute().getContent();
    } catch (IllegalArgumentException e) {
        log.warn("File '{}' could not be downloaded, illegal argument: {}", file.toString(), e.getMessage());
        throw e
    } catch (HttpResponseException e) {
        throw e;
    } catch (Exception e) {
        throw e;
    }
}
```
SDK Approach
```java
    public InputStream download() throws IOException {
            return client.files()
                    .get(file.getId())
                    .executeMediaAsInputStream();
    }
```

#### Stack trace
```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request Bad Request 
at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150) 
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40) 
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321) 
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067) 
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) 
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) 
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:380) 
at com.google.api.services.drive.Drive$Files$Get.executeMedia(Drive.java:5765) 
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMediaAsInputStream(AbstractGoogleClientRequest.java:523)
at com.google.api.services.drive.Drive$Files$Get.executeMediaAsInputStream(Drive.java:5760)
```

#### External references such as API reference guides

- none

Thanks!
Ram

**Comment by lesv** [comment]
@sqrrrl Perhaps this is for your team?

**Comment by sqrrrl** [comment]
Unfortunately we're not equipped to help out at the moment, but there is a pilot program (no SLOs yet) for developer support starting up that might be a good option. Only restriction is it does require a paid Workspace account to file, though unlike enterprise support, it's open to all users in a domain.

https://support.google.com/a/contact/wsdev

**Comment by meltsufin** [comment]
@rvirsingh Please contact GCP Support. We are closing the issue for now, but feel free to reopen later.
