### ISSUE TITLE
StreamCorruptedException trying to get oauth token

### ISSUE THREAD

**Issue by javamonkey79** [googleapis/google-api-java-client#2366]
We're getting the following exception when trying to get an oauth token:

StreamCorruptedException: invalid handle value: 007E0075
	at java.io.ObjectInputStream.readHandle(ObjectInputStream.java:1785)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1843)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2073)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1656)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460)
	at java.util.HashMap.readObject(HashMap.java:1418)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2321)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460)
	at com.google.api.client.util.IOUtils.deserialize(IOUtils.java:166)
	at com.google.api.client.util.store.FileDataStoreFactory$FileDataStore.<init>(FileDataStoreFactory.java:119)
	at com.google.api.client.util.store.FileDataStoreFactory.createDataStore(FileDataStoreFactory.java:90)
	at com.google.api.client.util.store.AbstractDataStoreFactory.getDataStore(AbstractDataStoreFactory.java:54)
	at com.google.api.client.auth.oauth2.StoredCredential.getDefaultDataStore(StoredCredential.java:165)
	at com.google.api.client.auth.oauth2.AuthorizationCodeFlow$Builder.setDataStoreFactory(AuthorizationCodeFlow.java:804)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.setDataStoreFactory(GoogleAuthorizationCodeFlow.java:225)

This is for v1.10.0

**Comment by lqiu96** [comment]
Hi, would you be able to provide us a reproducer?

**Comment by javamonkey79** [comment]
@lqiu96 that's tricky since the calling code is a mix of open source google api code and our internal code. So, I don't think I could share it here. It looks like you are on the team at google, so if there is a way to submit the code in more private way, I could do that. 

Otherwise, I could provide a rough overview:

1. We have 5 threads pulling data from 7 accounts
2. Each account has up to 2k properties it is trying to download
3. Mid way through the job, we start getting this error: `com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.`
4. So, I put in logic to detect this error and log back in. 

That's when I get the stream corrupted exception.

**Comment by lqiu96** [comment]
If you have a support contract with GCP, the easiest way would to each out via the [support console](https://cloud.google.com/support/) and it would be easy to connect via that channel.

Otherwise, we can try and debug via GH. it's a bit hard for challenging for us to figure out what is the issue based on the stack trace. If it's not too much work, would you be able to build a minimal reproducer for us to begin debugging? I think for starters we would be looking for some calling code and the dependencies you're pulling in.

This does seem like an Auth issue (just from a quick glance). If you have a repro, I can try and confirm it and then CC some of the Java Auth folks to take a look.

**Comment by meltsufin** [comment]
Closing due to inactivity. Please re-open if the issue persists and you have new information to share.
