### ISSUE TITLE
Fail to build gcp client in fips compliant mode 

### ISSUE THREAD

**Issue by jazzyMix** [googleapis/google-api-java-client#2404]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
I have contacted GCP support, they ask me to open a github issue instead.

**Is your feature request related to a problem? Please describe.**
What the problem is. Example: I'm always frustrated when [...]
Context: I am making our service FIPS compliant, we depends on https://github.com/tink-crypto/tink-java-gcpkms which depends on this library. When we start the kms client it is using this library and fail to open this file https://github.com/googleapis/google-api-java-client/blob/main/google-api-client/src/main/resources/com/google/api/client/googleapis/google.p12 
```

java.security.GeneralSecurityException: cannot build GCP KMS client
	at com.google.crypto.tink.integration.gcpkms.GcpKmsClient.withCredentials(GcpKmsClient.java:141)
	at com.google.crypto.tink.integration.gcpkms.GcpKmsClient.withDefaultCredentials(GcpKmsClient.java:155)
.
.
.

Caused by: java.io.IOException: parseAlgParameters failed: PBE AlgorithmParameters not available
	at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:855)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2113)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at com.google.api.client.util.SecurityUtils.loadKeyStore(SecurityUtils.java:80)
	at com.google.api.client.googleapis.GoogleUtils.getCertificateTrustStore(GoogleUtils.java:86)
	at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:87)
	at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:58)
	at com.google.crypto.tink.integration.gcpkms.GcpKmsClient.withCredentials(GcpKmsClient.java:135)
	... 4 more
Caused by: java.security.NoSuchAlgorithmException: PBE AlgorithmParameters not available
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
	at java.base/java.security.Security.getImpl(Security.java:676)
	at java.base/java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:157)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:849)
	... 12 more
```

i checked 
❯ openssl pkcs12 -in google.p12 -info
Enter Import Password:
MAC: sha1, Iteration 100000
MAC length: 20, salt length: 20
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 50000
my guess is it failed because  RC2 is not secure enough, since this file is baked in in the repo, i am not sure if there is anything we can do 

**Describe the solution you'd like**
Generate this file using a stronger/FIPS compliant algorithm

**Describe alternatives you've considered**
If we can continue to use tink-java-gcpkms without this dependency that is also doable but i doubt it

**Additional context**
Any other context or screenshots about the feature request.

**Comment by mpeddada1** [comment]
cc: @googleapis/googleapis-auth

**Comment by jazzyMix** [comment]
hi may I get some eyes on this ? @googleapis/googleapis-auth

**Comment by TimurSadykov** [comment]
@mpeddada1 this seems to be related  to transport settings, and their support of FIPS compliant cyphers.

**Comment by meltsufin** [comment]
@jazzyMix Please provide your support case number or ask the support person to contact the internal Cloud SDK Java team.
