### ISSUE TITLE
Issue Insufficient data written

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#781]
_From [satish.d...@gmail.com](https://code.google.com/u/106841029675152776760/) on May 16, 2013 03:00:56_

Which Google API and version (e.g. Google Calendar API version 3)? Java environment (e.g. Java 6, Android 2.3, App Engine)? External references, such as API reference guide? Please provide any additional information below. Hi Team,
we are updated google api to 1.15.0-rc, but we are still getting insufficient data written error: what could be the most appropriate chunk size for uploading file.
Error:

```
java.io.IOException: insufficient data written
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(Unknown Source)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:960)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:482)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:390)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:418)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.uploadFile(GoogleDriveService.java:421)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.saveFileToDrive(GoogleDriveService.java:142)
    at WebShortCut.Application.GoogleDrive.WebShortCutApp.qUploadFile(WebShortCutApp.java:537)
    at WebShortCut.test.FileUploadTest$RequestFileUpload.run(FileUploadTest.java:75)
    at java.lang.Thread.run(Unknown Source)
```

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=780_

**Comment by medaminebh** [comment]
http://stackoverflow.com/a/30796105/4576135

**Comment by fonzy2013** [comment]
Is there anything I can do to speed up a resolution of this issue? We are seeing many of these exceptions while using gcloud-java, issue is reported here https://github.com/GoogleCloudPlatform/gcloud-java/issues/1018

**Comment by ajaaym** [comment]
this seems fixed.
