### ISSUE TITLE
 insufficient data written

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#782]
_From [akhi85pr...@gmail.com](https://code.google.com/u/112014540297076272624/) on May 16, 2013 12:12:20_

Version of google-api-java-client : 1.15.0-rc

Java environment : jdk-7u17-windows-i586

Describe the problem:

i was using goolge-api-clint 1.10.3-beta and commonly getting this "i.e insufficient data witting exception" while uploading files. the chunk size used in the application was 10MB.we also changed the chunk size to 256kb/1mb but the problem remains the same, then we decided to update the API to 1.15.0-rc. But we are still  facing the same problem. This issue is destroying my project.  Pls help?
 Exception trace: 

java.io.IOException: insufficient data written
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(Unknown Source)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:960)
    at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:482)
    at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:390)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:418)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.uploadFile(GoogleDriveService.java:715)
    at WebShortCut.Application.GoogleDrive.GoogleDriveService.saveFileToDrive(GoogleDriveService.java:168)
    at WebShortCut.Application.GoogleDrive.WebShortCutApp.qUploadFile(WebShortCutApp.java:537)
    at WebShortCut.test.FileUploadTest$RequestFileUpload.run(FileUploadTest.java:75)
    at java.lang.Thread.run(Unknown Source) How would you expect it to be fixed?

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=781_

**Comment by medaminebh** [comment]
http://stackoverflow.com/a/30796105/4576135

**Comment by chajath** [comment]
Looks like a very unfortunate consequence of how `sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream#close` does not gracefully check for error state before attempting to validate bytes written and throws another exception if the validation doesn't check out. ([See the code](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L3187)) I suspect the original issue might have been caused by some other IO issue but since this close call, which is called from finally {} is throwing an exception that original cause might have been lost.

As a workaround (so at least programmer can see what the underlying issue was), I think NetHttpRequest should catch the exception, log the exception and rethrow it

**Comment by ajaaym** [comment]
This seems fixed.
