### ISSUE TITLE
Google Sheets APIs would get errors "Unrecognized content type_application/binary" occassionally

### ISSUE THREAD

**Issue by angeloh** [googleapis/google-api-java-client#983]
This is our code:
https://gist.github.com/angeloh/49d3dd33ec7896a05337

We are getting this error occasionally for some users. Can you please help?

```
[warn] application - Some error when try to get SheetInfo
com.google.gdata.util.ParseException: Unrecognized content
type:application/binary
     at com.google.gdata.client.Service.parseResponseData(Service.java:2136)
~[com.google.gdata.core-1.47.1.jar:na]
     at com.google.gdata.client.Service.parseResponseData(Service.java:2098)
~[com.google.gdata.core-1.47.1.jar:na]
     at com.google.gdata.client.Service.getFeed(Service.java:1136)
~[com.google.gdata.core-1.47.1.jar:na]
     at com.google.gdata.client.Service.getFeed(Service.java:998)
~[com.google.gdata.core-1.47.1.jar:na]
     at
com.google.gdata.client.GoogleService.getFeed(GoogleService.java:645)
~[com.google.gdata.core-1.47.1.jar:na]
```

**Comment by sduskis** [comment]
I'm going to close this as obsolete.  Please reopen if this is still an issue.
